### ISSUE TITLE
Where to put music and what format

### ISSUE THREAD

**Issue by supercreate01** [ninjawarrior1337/f0-pifm-c#1]
I looked at this project and I think it plays music on an FM band. Where do you put the music and in what format.

**Comment by ninjawarrior1337** [comment]
Yes! but instead of actually playing music over the FM band standalone, this is more just a frontend to a control application that runs on a Raspberry Pi 0 that is plugged into the Flipper and communicates over UART. 
https://github.com/ninjawarrior1337/rpi-pifm-kt is the server app and you would have to enable UART on the Pi, compile the Java binary and put it alongside a pi_fm_rds binary and some .wav files.

**Comment by supercreate01** [comment]
Ah, thank you!
